### ISSUE TITLE
[CRASH] Remova o SERVER (IP ou Domínio) e OK, na segunda vez CRASH

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/otclient#620] opened 2023-11-05 22:04 UTC
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

![image](https://github.com/mehah/otclient/assets/6209529/a1ef1d7f-3101-4890-96aa-e9562969cdf4)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csantbr** [comment] 2023-11-06 03:01
I couldn't reproduce it with the 10.98 protocol. What are the settings on your machine?

**Comment by csantbr** [comment] 2023-11-06 03:07
I couldn't reproduce it with the 10.98 protocol. What are the settings on your machine?

**Comment by luanluciano93** [comment] 2023-11-06 03:21
i5 16gb ssd

**Comment by conde2** [comment] 2023-11-15 12:53
I couldn't reproduce either, (compiled with latest commit in windows) must be something on your end. I will be closing the issue, if any further information please open a new issue.

https://github.com/mehah/otclient/assets/2137569/5675a10a-9ac4-4533-999c-8c65098c06dd

**Closed as completed by conde2** 2023-11-15 12:53 UTC
Labels: Priority: Low, Status: Pending Test, Type: Bug
